Varna:
  - Abandoned church
  - Garage
  - Chop Shop
  - Growhouse
  - Tattoo Parlor
  - Salon
  - Corner Tavern
  - Drug House
  - Open Air Market
  - Mortuary
  - Hideout
  - Hotel
  - Miasma Plant
  - Building Under Construction
  - Apartment block
  - Gotberg Embassy
  - Steamworks
  - Club
  - Raided estate
  - Bathhouse
  - Library
  - Hospice
  - Prison
  - Bunker
  - Bank
  - Armory
  - Kennel
  - Restaurant
  - Casino
  - Sewers 
  - Headquarters
  - Necropolis
The Wilds:
  - The Titanness
  - Deep Blue Oceans
  - Gaea's Navel
  - Lord's Forests
  - Corrupted Saltmarshes
  